use_frameworks!

platform :ios, '8.0'

target 'SHNetworking_Example' do
  pod 'SHNetworking', :path => '../'

  target 'SHNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
